[package]
name = "formic-core"
version = "0.1.1"
edition = "2024"

[dependencies]
formic-common = { path = "../../libs/formic-common" }

nickel-lang-core = "0.18"
notify = "6.1"
sysinfo = "0.30"
winreg = "0.52"
netstat2 = "0.9"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_WinTrust",
    "Win32_Security_Cryptography_Catalog",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
] }
winsafe = { version = "0.0.19", features = ["kernel"] }